#!/usr/bin/env zsh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
	# install homebrew if it's missing
	if ! command -v brew >/dev/null 2>&1; then
		echo "Installing homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi

	echo "Setting iTerm preference folder"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "$XDG_CONFIG_HOME/iterm2"
fi
