#!/bin/zsh

# Install Homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
	echo "Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOMEBREW_BUNDLE_FILE" ]; then
	echo "Updating Homebrew bundle..."
	brew bundle
else
	echo "Warning: No Brewfile found!"
fi

