tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "yadm"
brew "zsh-syntax-highlighting"
brew "neovim", args: ["HEAD"]
brew "neofetch"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"

cask "font-iosevka"
cask "iterm2"

cask "obsidian"
